"""Generate a short, reproducible terminal-style demo GIF of the FastAPI POC.

Rubric context: Step 8 (Deployment & MLOps) asks for "a demo (GIF/screencast)"
alongside the running app. This project's deployment is a local FastAPI
proof of concept (`src/app.py`), so this script renders a short animated GIF
that walks through calling its three endpoints (`/health`, `/model/metadata`,
`/forecast`) in order.

The JSON shown in each frame is not hand-written sample text: it is captured
live from the real app via FastAPI's `TestClient` (the same in-process
mechanism `tests/test_project_contracts.py` uses), so the demo always
reflects whatever model/metadata is actually persisted under `models/` when
this script is run. Re-run it after re-persisting the model so the demo
never drifts from actual behavior.

No real network server, terminal emulator or screen recorder is used - this
is a lightweight, fully offline, deterministic substitute built with Pillow,
appropriate for a historical-backtest local POC rather than a hosted
service.

Usage:
    python -m src.generate_deployment_demo
"""

import json
import textwrap
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
MEDIA_DIR = ROOT / "docs" / "media"
OUTPUT_GIF = MEDIA_DIR / "deployment_demo.gif"

WIDTH, HEIGHT = 900, 560
BG_COLOR = (18, 18, 22)
HEADER_COLOR = (45, 45, 52)
PROMPT_COLOR = (120, 220, 140)
TEXT_COLOR = (225, 225, 225)
CAPTION_COLOR = (170, 170, 180)
FRAME_MS = 3200
WRAP_WIDTH = 100


def _load_font(size: int) -> ImageFont.FreeTypeFont:
    for candidate in ("consola.ttf", "Consolas.ttf", "DejaVuSansMono.ttf", "cour.ttf"):
        try:
            return ImageFont.truetype(candidate, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _capture_live_responses() -> list[dict]:
    """Call the real app in-process and return the actual JSON responses."""
    from fastapi.testclient import TestClient

    from src.app import app

    client = TestClient(app)
    calls = [
        ("GET /health", "/health"),
        ("GET /model/metadata", "/model/metadata"),
        ("GET /forecast?horizon_days=7", "/forecast?horizon_days=7"),
    ]
    captured = []
    for label, path in calls:
        response = client.get(path)
        body = response.json()
        if path.startswith("/forecast") and isinstance(body.get("forecast"), list):
            body = dict(body)
            body["forecast"] = body["forecast"][:3] + [
                {"...": f"{len(response.json()['forecast']) - 3} more day(s) truncated for this demo frame"}
            ]
        captured.append(
            {
                "label": label,
                "status": response.status_code,
                "body": json.dumps(body, indent=2),
            }
        )
    return captured


def _render_frame(title: str, command: str, status: int, body_text: str, caption: str) -> Image.Image:
    image = Image.new("RGB", (WIDTH, HEIGHT), BG_COLOR)
    draw = ImageDraw.Draw(image)
    font_header = _load_font(16)
    font_mono = _load_font(15)
    font_caption = _load_font(14)

    draw.rectangle([0, 0, WIDTH, 34], fill=HEADER_COLOR)
    draw.text((14, 9), title, font=font_header, fill=(230, 230, 235))

    y = 52
    draw.text((16, y), f"$ curl http://127.0.0.1:8000{command}", font=font_mono, fill=PROMPT_COLOR)
    y += 26
    draw.text((16, y), f"HTTP {status}", font=font_mono, fill=(240, 200, 120))
    y += 24

    for raw_line in body_text.splitlines():
        for line in textwrap.wrap(raw_line, WRAP_WIDTH) or [""]:
            draw.text((16, y), line, font=font_mono, fill=TEXT_COLOR)
            y += 18
            if y > HEIGHT - 60:
                break
        if y > HEIGHT - 60:
            break

    draw.rectangle([0, HEIGHT - 44, WIDTH, HEIGHT], fill=HEADER_COLOR)
    for line_no, line in enumerate(textwrap.wrap(caption, 110)[:2]):
        draw.text((14, HEIGHT - 40 + line_no * 16), line, font=font_caption, fill=CAPTION_COLOR)
    return image


def build_gif() -> None:
    MEDIA_DIR.mkdir(parents=True, exist_ok=True)
    responses = _capture_live_responses()
    captions = [
        "Step 1/3: health check - reports whether a persisted model/metadata pair is available.",
        "Step 2/3: model metadata - identifies the persisted model, training window and limitations.",
        "Step 3/3: forecast - point-estimate daily counts starting the day after training history ends.",
    ]
    intro = _render_frame(
        title="Help Desk Ticket Volume Forecast \u2014 local FastAPI POC demo",
        command="  (uvicorn src.app:app --host 127.0.0.1 --port 8000)",
        status="-",
        body_text="Starting the local proof-of-concept API...\nNot a hosted or production service.",
        caption="This GIF is generated by src/generate_deployment_demo.py from the real app's live TestClient responses.",
    )
    frames = [intro]
    for response, caption in zip(responses, captions):
        frames.append(
            _render_frame(
                title="Help Desk Ticket Volume Forecast \u2014 local FastAPI POC demo",
                command=response["label"].split(" ", 1)[1],
                status=response["status"],
                body_text=response["body"],
                caption=caption,
            )
        )
    outro = _render_frame(
        title="Help Desk Ticket Volume Forecast \u2014 local FastAPI POC demo",
        command="  (Ctrl+C stops the local server)",
        status="-",
        body_text="Demo complete. This is a historical-backtest local POC,\nnot a live/current production forecasting service.",
        caption="See docs/deployment_monitoring.md for the full API contract, monitoring plan and rollback procedure.",
    )
    frames.append(outro)

    durations = [2600] + [FRAME_MS] * len(responses) + [2600]
    frames[0].save(
        OUTPUT_GIF,
        save_all=True,
        append_images=frames[1:],
        duration=durations,
        loop=0,
        optimize=True,
    )
    if not OUTPUT_GIF.is_file() or OUTPUT_GIF.stat().st_size == 0:
        raise RuntimeError("Failed to write a valid demo GIF.")
    print(f"Wrote {OUTPUT_GIF}")


if __name__ == "__main__":
    build_gif()
